feat:[CHK-4839] add integration test for migration job (#248)
* feat(integration-test): add js script for the integration test

* fix(integration-test): change the code for matching event, add comment

* fix(integration-test): fix

* feat(code-review-pipeline): add integration test stage

* fix(code-review-pipeline): fix

* fix(code-review-pipeline): fix

* chore(code-review-pipeline): add pagopaEcommerceLocal resource

* chore(code-review-pipeline): test

* fix(code-review-pipeline): fix mongo container name

* fix(code-review-pipeline): fix and add some test

* fix(code-review-pipeline): add code from pull request repository

* chore: add health proble variable in application.properties, some code-review test

* code-review testing

* chore: fix code review

* chore: fix code review

* Apply suggestion from @pietro-tota

* feat(code-review): change the code review to use different script for data test preparation and for check the result, point to the testing branch of ecommercelocal

* fix(code-review): fix

* fix(code-review): fix

* fix(code-review): remove --args and use env variable for pass testing data

* fix(code-review): remove --args and use env variable for pass testing data

* fix(code-review): fix wrong timeout setted

* fix(integration-test): remove the double script

* fix

* chore: remove migration integration test, change the branch of pagopaEcommerceLocal repo in codereview to main

* chore: extract the timeout value as external paramenter

* chore(integration-test): change the view migration config parameter to activate the job

* test: change the selected branch of ecommerce-local for testing

* chore(integration-test): change rate of the migration query and increase the waiting time

* chore(integration-test): fix sed command

* fix: remove sed to test

* chore(code-review): set the branch of ecommercelocal to main

---------

Co-authored-by: Pietro Tota <115724836+pietro-tota@users.noreply.github.com>

diff --git a/.devops/code-review-pipelines.yml b/.devops/code-review-pipelines.yml
--- a/.devops/code-review-pipelines.yml
+++ b/.devops/code-review-pipelines.yml
@@ -13,85 +13,141 @@ trigger:
 pool:
   vmImage: 'ubuntu-latest'
 
+resources:
+  repositories:
+    - repository: pagopaEcommerceLocal
+      type: github
+      name: pagopa/pagopa-ecommerce-local
+      ref: main
+      endpoint: 'io-azure-devops-github-ro'
+
 variables:
   MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
   MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
+  BRANCH_NAME: $[ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') ]
 
-steps:
-  - task: Cache@2
-    inputs:
-      key: 'maven | "$(Agent.OS)" | pom.xml'
-      restoreKeys: |
-        maven | "$(Agent.OS)"
-        maven
-      path: $(MAVEN_CACHE_FOLDER)
-    displayName: Cache Maven local repo
+stages:
+  - stage: BuildAndUnitTest
+    jobs:
+      - job: make_buildAndUnitTest
+        steps:
+        - task: Cache@2
+          inputs:
+            key: 'maven | "$(Agent.OS)" | pom.xml'
+            restoreKeys: |
+              maven | "$(Agent.OS)"
+              maven
+            path: $(MAVEN_CACHE_FOLDER)
+          displayName: Cache Maven local repo
 
-  - task: SonarCloudPrepare@3
-    displayName: 'Prepare SonarCloud analysis configuration'
-    inputs:
-      SonarCloud: '$(SONARCLOUD_SERVICE_CONN)'
-      organization: '$(SONARCLOUD_ORG)'
-      scannerMode: Other
-      extraProperties: |
-        sonar.projectKey=$(SONARCLOUD_PROJECT_KEY)
-        sonar.projectName=$(SONARCLOUD_PROJECT_NAME)
-        sonar.coverage.exclusions=**/config/*,**/*Mock*,**/model/**,**/entity/*
-        sonar.coverage.jacoco.xmlReportPaths=./target/site/jacoco/jacoco.xml
-        sonar.junit.reportPaths=target/surefire-reports/
-        sonar.verbose=true
+        - task: SonarCloudPrepare@3
+          displayName: 'Prepare SonarCloud analysis configuration'
+          inputs:
+            SonarCloud: '$(SONARCLOUD_SERVICE_CONN)'
+            organization: '$(SONARCLOUD_ORG)'
+            scannerMode: Other
+            extraProperties: |
+              sonar.projectKey=$(SONARCLOUD_PROJECT_KEY)
+              sonar.projectName=$(SONARCLOUD_PROJECT_NAME)
+              sonar.coverage.exclusions=**/config/*,**/*Mock*,**/model/**,**/entity/*
+              sonar.coverage.jacoco.xmlReportPaths=./target/site/jacoco/jacoco.xml
+              sonar.junit.reportPaths=target/surefire-reports/
+              sonar.verbose=true
 
-  - bash: |
-      docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 mcr.microsoft.com/azure-storage/azurite &
-    displayName: Run azurite to test Service - Storage integration
 
-  # necessary step to make the authentication work
-  # removing it will cause the pipeline to fail when cache gets emptied
-  - task: Bash@3
-    displayName: 'Create Maven settings.xml'
-    inputs:
-      targetType: 'inline'
-      script: |
-        mkdir -p $(Pipeline.Workspace)/.m2
-        cat > $(Pipeline.Workspace)/.m2/settings.xml << EOF
-        <?xml version="1.0" encoding="UTF-8"?>
-        <settings>
-          <servers>
-            <server>
-              <id>github</id>
-              <username>token</username>
-              <password>${GITHUB_TOKEN}</password>
-            </server>
-          </servers>
-        </settings>
-        EOF
-    env:
-      GITHUB_TOKEN: $(GITHUB_RO_TOKEN)
+        - bash: |
+            docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 mcr.microsoft.com/azure-storage/azurite &
+          displayName: Run azurite to test Service - Storage integration
 
-  - task: Maven@4
-    displayName: 'Run Junit Tests'
-    inputs:
-      mavenPomFile: 'pom.xml'
-      mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
-      options: "-s $(Pipeline.Workspace)/.m2/settings.xml"
-      javaHomeOption: 'JDKVersion'
-      jdkVersionOption: '21'
-      jdkArchitectureOption: 'x64'
-      publishJUnitResults: false
-      testResultsFiles: '**/surefire-reports/TEST-*.xml'
-      goals: 'clean verify'
-      sonarQubeRunAnalysis: true
-    env:
-      GITHUB_TOKEN: $(GITHUB_RO_TOKEN)
+        # necessary step to make the authentication work
+        # removing it will cause the pipeline to fail when cache gets emptied
+        - task: Bash@3
+          displayName: 'Create Maven settings.xml'
+          inputs:
+            targetType: 'inline'
+            script: |
+              mkdir -p $(Pipeline.Workspace)/.m2
+              cat > $(Pipeline.Workspace)/.m2/settings.xml << EOF
+              <?xml version="1.0" encoding="UTF-8"?>
+              <settings>
+                <servers>
+                  <server>
+                    <id>github</id>
+                    <username>token</username>
+                    <password>${GITHUB_TOKEN}</password>
+                  </server>
+                </servers>
+              </settings>
+              EOF
+          env:
+            GITHUB_TOKEN: $(GITHUB_RO_TOKEN)
 
-  - task: SonarCloudPublish@3
-    displayName: 'Publish SonarCloud results on build summary'
-    inputs:
-      pollingTimeoutSec: '300'
+        - task: Maven@4
+          displayName: 'Run Junit Tests'
+          inputs:
+            mavenPomFile: 'pom.xml'
+            mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
+            options: "-s $(Pipeline.Workspace)/.m2/settings.xml"
+            javaHomeOption: 'JDKVersion'
+            jdkVersionOption: '21'
+            jdkArchitectureOption: 'x64'
+            publishJUnitResults: false
+            testResultsFiles: '**/surefire-reports/TEST-*.xml'
+            goals: 'clean verify'
+            sonarQubeRunAnalysis: true
+          env:
+            GITHUB_TOKEN: $(GITHUB_RO_TOKEN)
 
-  - task: PublishCodeCoverageResults@2
-    inputs:
-      codeCoverageTool: 'JaCoCo'
-      summaryFileLocation: 'target/site/jacoco/jacoco.xml'
-      reportDirectory: 'target/site/jacoco'
-    displayName: 'Publish Code Coverage on Azure Devops'
+        - task: SonarCloudPublish@3
+          displayName: 'Publish SonarCloud results on build summary'
+          inputs:
+            pollingTimeoutSec: '300'
+
+        - task: PublishCodeCoverageResults@2
+          inputs:
+            codeCoverageTool: 'JaCoCo'
+            summaryFileLocation: 'target/site/jacoco/jacoco.xml'
+            reportDirectory: 'target/site/jacoco'
+          displayName: 'Publish Code Coverage on Azure Devops'
+
+  - stage: IntegrationTest
+    dependsOn: [ ]
+    jobs:
+      - job: make_integration_test
+        steps:
+          - checkout: pagopaEcommerceLocal
+          - script: |
+              echo "##[debug] Change placeholder for ecommerce-transaction-scheduler-service set branch: $(BRANCH_NAME)"
+              sed -i "s|^ECOMMERCE_TRANSACTIONS_SCHEDULER_COMMIT_SHA=.*$|ECOMMERCE_TRANSACTIONS_SCHEDULER_COMMIT_SHA=$(BRANCH_NAME)|" .env
+              echo "##[debug] Set the value of the MIGRATION_TRANSACTION_BATCH_EVENTSTORE_CRON_EXPRESSION and MIGRATION_TRANSACTION_BATCH_TRANSACTIONS_VIEW_CRON_EXPRESSION to activate the migration jobs"
+              sed -i "s|^MIGRATION_TRANSACTION_BATCH_EVENTSTORE_CRON_EXPRESSION=.*$|MIGRATION_TRANSACTION_BATCH_EVENTSTORE_CRON_EXPRESSION=\"*/5 * * * * *\"|" pagopa-ecommerce-transactions-scheduler-service/transactions-scheduler-service.env
+              sed -i "s|^MIGRATION_TRANSACTION_BATCH_TRANSACTIONS_VIEW_CRON_EXPRESSION=.*$|MIGRATION_TRANSACTION_BATCH_TRANSACTIONS_VIEW_CRON_EXPRESSION=\"*/5 * * * * *\"|" pagopa-ecommerce-transactions-scheduler-service/transactions-scheduler-service.env
+            displayName: 'Change transaction branch name ecommerce-local .env'
+          - script: |
+              cd $(Build.SourcesDirectory)/pagopa-ecommerce-local
+              docker compose up mongo redis storage azurite-init pagopa-ecommerce-transactions-scheduler-service -d
+            displayName: 'Run app with docker-compose'
+            env:
+              GITHUB_TOKEN: $(GITHUB_RO_TOKEN)
+          - script: |
+              timeout 180 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8091/actuator/health)" != "200" ]]; do sleep 5; done' || exit 1
+            displayName: 'Health check'
+          - script: |
+              echo "Starting integration testing of the migration process..."
+
+              docker cp api-tests/transaction-scheduler-service/migration-integration-test.js pagopa-ecommerce-mongo:/tmp/migration-integration-test.js
+              
+              TIMEOUT=30000
+              docker exec -e TIMEOUT="$TIMEOUT" pagopa-ecommerce-mongo mongosh -u admin -p password --authenticationDatabase admin \
+              --quiet /tmp/migration-integration-test.js
+            displayName: 'Integration test of the migration process.'
+          - script: |
+              echo "Printing logs for all running containers:"
+              for container in $(docker ps -q); do
+                name=$(docker inspect --format='{{.Name}}' $container | sed 's/^\/\(.*\)/\1/')
+                echo "===== Logs for $name ====="
+                docker logs $container
+                echo "===== End of logs for $name ====="
+              done
+            condition: always()
+            displayName: 'Print Docker container logs'
